### ISSUE TITLE
Include Youtube Link in jupyter notebook lecture

### ISSUE THREAD

**Issue by yyouss1** [webartifex/intro-to-python#10]
Hi Alex, 

Found your course on Hacker News - really excited about spending time learning Python.  Please include the Youtube Links in the actual jupyter notebook lectures. Right now the only place with the links is on Hacker News, if you find this course through other channels, you will not know that there are corresponding video lectures on Youtube. 

Also - I'm not sure if this is covered in the course yet, but a short introduction to Git would also be useful! 

Thanks!

**Comment by webartifex** [comment]
Links are now included.

@yyouss1 Thanks for letting me know about this :)
